API_HOST_URL: 'http://localhost:8000'
APPLICATION_ID: 'org.openedx.app'
ENVIRONMENT_DISPLAY_NAME: 'Localhost'
URI_SCHEME: ''
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'
FAQ_URL: ''
OAUTH_CLIENT_ID: 'OAUTH_CLIENT_ID'

# Keep empty to hide setting
AGREEMENT_URLS:
  PRIVACY_POLICY_URL: ''
  COOKIE_POLICY_URL: ''
  DATA_SELL_CONSENT_URL: ''
  TOS_URL: ''
  EULA_URL: ''
  SUPPORTED_LANGUAGES: [ ] #en is default language

DISCOVERY:
  TYPE: 'native'
  WEBVIEW:
    BASE_URL: ''
    COURSE_DETAIL_TEMPLATE: ''
    PROGRAM_DETAIL_TEMPLATE: ''

PROGRAM:
  TYPE: 'native'
  WEBVIEW:
    BASE_URL: ''
    PROGRAM_DETAIL_TEMPLATE: ''

DASHBOARD:
  TYPE: 'gallery'

FIREBASE:
  ENABLED: false
  CLOUD_MESSAGING_ENABLED: false
  PROJECT_NUMBER: ''
  PROJECT_ID: ''
  APPLICATION_ID: '' #App ID field from the Firebase console or mobilesdk_app_id from the google-services.json file.
  API_KEY: ''

BRAZE:
  ENABLED: false
  PUSH_NOTIFICATIONS_ENABLED: false

GOOGLE:
  ENABLED: false
  CLIENT_ID: ''

MICROSOFT:
  ENABLED: false
  CLIENT_ID: ''
  PACKAGE_SIGNATURE: ''

FACEBOOK:
  ENABLED: false
  FACEBOOK_APP_ID: ''
  CLIENT_TOKEN: ''

BRANCH:
  ENABLED: false
  KEY: ''
  URI_SCHEME: ''
  HOST: ''
  ALTERNATE_HOST: ''

#Platform names
PLATFORM_NAME: "OpenEdX"
PLATFORM_FULL_NAME: "OpenEdX"
#App sourceSets dir
THEME_DIRECTORY: "openedx"
#tokenType enum accepts JWT and BEARER only
TOKEN_TYPE: "JWT"
#feature flag for activating Whatâ€™s New feature
WHATS_NEW_ENABLED: false
#feature flag enable Social Login buttons
SOCIAL_AUTH_ENABLED: false
#feature flag to enable registration from app
REGISTRATION_ENABLED: true
#feature flag to do the authentication flow in the browser to log in
BROWSER_LOGIN: false
#feature flag to do the registration for in the browser
BROWSER_REGISTRATION: false
#Course navigation feature flags
UI_COMPONENTS:
  COURSE_DROPDOWN_NAVIGATION_ENABLED: false
  COURSE_UNIT_PROGRESS_ENABLED: false
  COURSE_DOWNLOAD_QUEUE_SCREEN: false
