build:
  maxIssues: 3000
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1

config:
  validation: true

processors:
  active: true
  exclude:
    - 'FunctionCountProcessor'
    - 'PropertyCountProcessor'

console-reports:
  active: true

naming:
  active: true
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Za-z0-9]*'
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
    privatePropertyPattern: '(_)?[A-Za-z][A-Za-z0-9]*'
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
    excludeClassPattern: '$^'

style:
  active: true
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '100'
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - 'Preview'

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false
  PrintStackTrace:
    active: false
